mqtt:
  host: mqtt
  user:
  password:

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.x.251:554/streamtype=0
          roles:
            - detect
            - record

  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.x.252:554/streamtype=0
          roles:
            - detect
            - record

  cam3:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@192.168.x.253:554/streamtype=0
          roles:
            - detect
            - record
